import Navbar from '../Components/Navbar'
import Head from 'next/head'
import style from '../styles/Home.module.css'


export default function Home() {
  return (
    <div >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main >
        <Navbar />
        <h1 >
          Welcome to <a href="https://nextjs.org">Gambia Tech Project!</a>
        </h1>

        
      </main>

      <footer className={style.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span >
            copyright 2022 AlbadDev
          </span>
        </a>
      </footer>
    </div>
  )
}
